### ISSUE TITLE
Item DSL brings IntelliJ to crash

### ISSUE THREAD

**Issue by NyCodeGHG** [JohnnyJayJay/spiglin#9]
Everytime when I try to use the Item DSL IntelliJ crashes. Then I have to kill it with the task manager.

Windows 10 2004
IntelliJ IDEA Ultimate 2020.2.3
with Plugins:

* .ignore
* Code With Me
* Discord Integration
* EnvFile
* Kotlin 1.4.10-release-IJ2020.2-1
* Ktor 1.4.1
* One Dark Theme
* Package Search

I'm using the latest version of spiglin.
Code example:
```kotlin
private enum class Page(val itemStack: ItemStack) {
        COLOR(item(Material.RED_DYE) {
            meta<ItemMeta> {
                name = "${BLUE}Farbe ändern"
            }
        })
    }
```

**Comment by JohnnyJayJay** [comment]
This seems like an issue on IntelliJ's or one of the plugins' end. The item DSL only consists of regular inline functions and properties and I'm not sure how I am supposed to fix this. I would recommend looking for the cause first and then report back/open an issue on the corresponding issue tracker.

**Comment by NyCodeGHG** [comment]
Ok, I will try with the IntelliJ EAP Version, maybe it's already fixed in that Version. I will close this issue, because it seems like it has nothing to do with spiglin.
